### PR TITLE
Multi view root

### PR DESCRIPTION
**Pull request by floryst**
Adds support for multiple views as renderers, rather than each View being a single render window.

Also adds an example to test/play with.

### CODE REVIEW

**Comment by floryst** [comment]
A video demonstration:

https://user-images.githubusercontent.com/1812167/166823263-317e5de7-e112-4958-b788-56d3e870759d.mov

Running the example usage will give a better sense of the functionality.

**Review by jourdain — APPROVED** [review]
LGTM

**Comment by jourdain** [comment]
Pretty cool what you've done!

**Pull request merged**
