### PR TITLE
fix: gh-pages publish

### PR DESCRIPTION
**Pull request by osiux**
Have no way to test if this works, but seems like on prev PR I forgot to build the docs before attempting to publish them 🤦‍♂️ hopefully this will fix it.

### CODE REVIEW

**Comment by floryst** [comment]
Thanks, that should do it. CI is not erroring out, so thanks again for fixing that.

**Comment by floryst** [comment]
I'm not yet entirely sure why it's complaining about a missing package, since running those steps locally works just fine.

**Comment by osiux** [comment]
> I'm not yet entirely sure why it's complaining about a missing package, since running those steps locally works just fine.

Looks like it's because it's using `npm ci` to install docs dependencies, somehow doesn't seems to work with the file reference in `package.json`, running that locally also fails. But `npm install` seems to work fine: #63 63

**Pull request merged**
