### PR TITLE
feat(View): forward browser events

### PR DESCRIPTION
**Pull request by FezVrasta**
Having access to the browser events is useful if you need to perform logic with the mouse position, modifier keys, etc.

This change should preserve backwards compatibility with the existing interface by adding a second argument to the event callbacks.

### CODE REVIEW

**Comment by jourdain** [comment]
Are you sure you are not running into some issue because of the debounce and the fact that react recycle events?

**Comment by FezVrasta** [comment]
React doesn't recycles events anymore starting from React 17, but even in older versions it would be enough to call `.persist()` if you needed the event to stick around for whatever reason.

I tested this extensively for a day and everything is working as intended, it allowed us to dramatically improve the performance of our custom-made widgets 🥳

**Comment by jourdain** [comment]
Can you add a vtk.js dependency in the example to see if that fix the ci? See https://github.com/Kitware/react-vtk-js/issues/32.

Thanks

**Pull request merged**
