### PR TITLE
React 18 and Typescript migration

### PR DESCRIPTION
**Pull request by floryst**
This (massive) PR (sorry) accomplishes three main things:
- Support for React 18 (yay)
- Written in Typescript (except for the examples)
- Hook based (to address some shortcomings with the class component implementations)

The commits themselves should be mostly self-contained and explanatory. I will collapse the earlier ones, as they do not conform to the commit message style. I may opt to close this and split up the commits into more manageable PRs.

This changes a lot of the API surface, with a few goals in mind, listed below. Since migrating to functional components necessitated a breaking change, I opted to clean up some of the API as I ported the components.
- nicer support for ESM
- Consistency of APIs
- Separation of vtk.js state update cycles from react update cycles

**This is still a WIP**. In fact, I aim to generate a beta release with these changes before releasing this on the main distribution.

Outstanding tasks:
- [ ] There are a few components that have not yet been ported. The minimal goal is to re-enable every example under the `usage` directory.
- [x] A breaking changes + migration doc is in order.
- [ ] Rebase onto main.
- [ ] Export types.

### CODE REVIEW

**Comment by jadh4v** [comment]
Just for tracking to-do items, this PR should also address #99 and #100 
Or maybe in separate future PRs if we think this is already a massive update.

**Comment by FezVrasta** [comment]
Do you think you could publish a pre-release on npm to make it easier to test this?

**Comment by floryst** [comment]
This is now targeting the beta branch, which should cut a beta release. @jadh4v @jourdain @FezVrasta if you would like to do a high-level pass-over or would like me to break up the commits into smaller PRs, let me know.

**Comment by jourdain** [comment]
All good from me. Thanks for taking the lead on that!

**Pull request merged**
