### PR TITLE
bump(vtk.js): to version 29.4.5

### PR DESCRIPTION
**Pull request by jadh4v**

### CODE REVIEW

**Comment by jadh4v** [comment]
@floryst I only manually upgraded vtk-js to 29.4.5. Do we want to do a general `npm upgrade` for all packages?

Also do we need to do anything regarding this msg:
```
10 vulnerabilities (6 moderate, 2 high, 2 critical)

To address issues that do not require attention, run:
  npm audit fix
```

**Comment by floryst** [comment]
No need for upgrading all other packages for this PR, but we definitely want to.

**Pull request merged**
