### PR TITLE
Support user defined color map preset

### LINKED ISSUE #139: Support customized colorMap
Hi, is it possible to support customized color map in GeometryRepresentation component?

I'll try to issue a PR for this.

### PR DESCRIPTION
**Pull request by sigmama**
Context:
Add user defined color map preset

Result:
Users will be able to pass in customized colormap preset with colorMapPreset prop in related representation components.

### CODE REVIEW

**Comment by sigmama** [comment]
Hi @floryst, please have a check. This is related to  https://github.com/Kitware/react-vtk-js/issues/139

**Review by floryst — APPROVED** [review]

**Comment by floryst** [comment]
Thanks for adding the feature!

**Pull request merged**
