### PR TITLE
feat: add color + opacity funcs to slice + volume

### PR DESCRIPTION
**Pull request by floryst**
Adds support for providing color and opacity transfer functions to both the Slice and Volume representations.

### CODE REVIEW

**Comment by floryst** [comment]
FYI @jadh4v

**Comment by danyim** [comment]
Thanks for exposing those properties. Would it be possible to also export a utility function that would accept a [IColorMapPreset](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Core/ColorTransferFunction/ColorMaps.d.ts#L7-L15) and output the color transfer and scalar opacity functions?

**Comment by floryst** [comment]
> Thanks for exposing those properties. Would it be possible to also export a utility function that would accept a [IColorMapPreset](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Core/ColorTransferFunction/ColorMaps.d.ts#L7-L15) and output the color transfer and scalar opacity functions?

You can convert presets into a color transfer function via `colorTransferFunction.applyColorMap(preset)`.

**Comment by danyim** [comment]
> You can convert presets into a color transfer function via `colorTransferFunction.applyColorMap(preset)`.

Understood, thanks for the tip

**Pull request merged**
