### PR TITLE
feat: new light export

### PR DESCRIPTION
**Pull request by FezVrasta**

### CODE REVIEW

**Comment by FezVrasta** [comment]
@jourdain I think we also need to expose umd/cjs in order for Jest and other bundlers to work correctly. I tried to build those but they assets weren't generated, do you think this is something you may look into?

**Comment by floryst** [comment]
Doesn't Jest and others provide a transform step to go from es to cjs? Or is this a different limitation you're talking about?

**Comment by jourdain** [comment]
@FezVrasta I probably won't have the time for a while sorry.

**Pull request merged**
