### PR TITLE
Add cutter example

### PR DESCRIPTION
**Pull request by dbertouille**
* Add vtkCutter to AvailableClasses to prevent tree-shaking
* Add an example of using the cutter

### CODE REVIEW

**Comment by jourdain** [comment]
Can you rename your commit so it could trigger a changelog + version automatically?

`fix(Cutter): Add vtkCutter class along with example`

**Comment by dbertouille** [comment]
For sure, should be fixed now.

**Comment by jourdain** [comment]
Thanks!

**Pull request merged**
