### PR TITLE
Add MIP rendering of PET data

### PR DESCRIPTION
**Pull request by sankhesh**
image

### CODE REVIEW

**Comment by sankhesh** [comment]
@floryst PTAL

**Comment by jadh4v** [comment]
This looks like a simple change. Can we merge this?

**Comment by jadh4v** [comment]
Also wondering why there are gaps in the volume. Is this a data problem or something else?

**Comment by sankhesh** [comment]
> Also wondering why there are gaps in the volume. Is this a data problem or something else?

I believe that's just how the data is.

> This looks like a simple change. Can we merge this?

I don't have the power to merge. @floryst Can you please?

**Comment by floryst** [comment]
Yep, merging now.

**Pull request merged**
