### PR TITLE
feat(View): mouseDown and mouseUp event handlers

### PR DESCRIPTION
**Pull request by FezVrasta**
This adds support for mouseDown and mouseUp event handlers, it follows the same API used for the `click` event handler.

I feel like the way the event handlers system is architected doesn't scale particularly well.

Note that I'm having a problem with the `mouseDown` event, it dosn't fire if I attach the event listener to the View `div`, probably vtk.js is swallowing the event during its `startDrag` event handling. I had to attach it directly to the canvas instead.

### CODE REVIEW

**Comment by jourdain** [comment]
> I feel like the way the event handlers system is architected doesn't scale particularly well.

Can you elaborate? The picking data/prop design is a requirement for `dash-vtk`. It does not mean you can not simply register proper callbacks on the react side of things without requiring such variable holder. But for sure we can not drop those event data holder due to dash design.

**Comment by FezVrasta** [comment]
Ok I see, it's just something very weird in the React space, I would expect the event handlers to be the sole responsible for this kind of behavior, and the consumer would then subscribe to them to receive the data.

**Comment by jourdain** [comment]
Yes I agree but `react-vtk-js` was born thanks to `dash` and `plotly`. But like I said, we could be more react friendly while keeping the features available to `dash-vtk`.

**Comment by jourdain** [comment]
ready to merge? Or do you want to do some edits?

**Comment by FezVrasta** [comment]
I've been testing it for the last 30 minutes and everything looks good to me.

**Pull request merged**
