### PR TITLE
build(vtk-js): update to the latest vtk-js

### PR DESCRIPTION
**Pull request by sankhesh**

### CODE REVIEW

**Comment by sankhesh** [comment]
@jourdain

**Comment by jourdain** [comment]
That won't trigger a new release which might be fine for your use case. Just let me know if I should merge or if you want to change the commit type?

**Comment by sankhesh** [comment]
Good point @jourdain. Will this trigger a minor/patch release or no release at all? What do you suggest for changes that update core dependencies like vtk-js? 

In my case, a minor release would be fine as it might still enable the application to pull latest react-vtk-js.

**Comment by jourdain** [comment]
minor release => `fix(vtk-js): Update to xx.xx.x`

**Comment by sankhesh** [comment]
@jourdain Could you please merge this?

**Pull request merged**
