### PR TITLE
feat(View): pointerSize property

### PR DESCRIPTION
**Pull request by FezVrasta**
I'm trying to understand why these changes aren't working, as soon I set a pointerSize larger than 0 picking stops working 🤔

### CODE REVIEW

**Comment by jourdain** [comment]
Make sure the xy are ints.

**Comment by FezVrasta** [comment]
No luck :-(

**Comment by jourdain** [comment]
What are the symptoms of the issue?

**Comment by FezVrasta** [comment]
No selection happens at all.

**Comment by jourdain** [comment]
Be aware that by changing x1/x2 to be different you will always get a [frustrum](https://github.com/Kitware/react-vtk-js/blob/master/src/core/View.js#L484) rather than a ray.

You may need to fix/extend the pick method to still perform the ray. Maybe by adding a bool arg for isFrustrum.

**Comment by FezVrasta** [comment]
Sorry I think I don't have enough knowledge on the matter to be helpful here :-(

**Comment by jourdain** [comment]
```
 pick(x1, y1, x2, y2, useFrustrum=false) {
      [...]
      if (useFrustrum) { // if (x1 !== x2 || y1 !== y2) {
      [...]
      const ray = [
        Array.from(
          this.openglRenderWindow.displayToWorld(Math.round((x1+x2) / 2), Math.round((y1+y2) / 2), 0, this.renderer)
        ),
        Array.from(
          this.openglRenderWindow.displayToWorld(Math.round((x1+x2) / 2), Math.round((y1+y2) / 2), 1, this.renderer)
        ),
      ];
      [...]
```

```
select => useFrustrum=true
click => useFrustrum=false
hover => useFrustrum=false
```

**Comment by FezVrasta** [comment]
So if `useFrustrum` is true I don't need to pass a ray to the `this.selections` map?

**Comment by jourdain** [comment]
Same code as before except the condition to detect if it is a click/hover=ray vs select=frustum is not based on the fact that x1 != x2. Otherwise you are changing the behavior of the selection.

**Comment by FezVrasta** [comment]
Thanks, it works now 👍

**Comment by jourdain** [comment]
You still need to fix the ray so it is at the center of the x1/x2/y1/y2 and not on one of the corner of the area.

**Comment by jourdain** [comment]
See my code snippet vs [original](https://github.com/Kitware/react-vtk-js/blob/master/src/core/View.js#L522-L527)

**Comment by jourdain** [comment]
All working? Ready to merge?

**Comment by FezVrasta** [comment]
CleanShot 2021-08-03 at 18 48 28

For some reason with the ray change it seems to be not centered.

**Comment by jourdain** [comment]
The ray/frustum part are only info metadata and don't affect selection. Maybe the returned array from hover is bigger than 1 and you always pick the first one? Check what the selection returned array looks like?

**Comment by FezVrasta** [comment]
I think it's just an optical effect due to the pointer shape, I enlarged the pointer area and it actually looks good 😇

**Pull request merged**
