### PR TITLE
feat(View): added keybindReset prop for optional reset binding

### PR DESCRIPTION
**Pull request by jun-sironamedical**
Removing reset camera keyboard 'r' binding

### CODE REVIEW

**Comment by floryst** [comment]
This removes functionality, but I agree with it given the changing use-cases for this library. @jourdain

**Comment by floryst** [comment]
Also, the commits should be formatted according to angular conventions in order for semantic-release to cut a release.

**Comment by jourdain** [comment]
This is definitely going to break dash usability. It would be nice if it was possible to make that reset camera optional so your usecase could be handle as well.

**Comment by jun-sironamedical** [comment]
pass a flag to optionally bind reset instead?

@floryst I will mend the commits

**Comment by jun-sironamedical** [comment]
closing: branch name

**Comment by jun-sironamedical** [comment]
reopened - https://github.com/Kitware/react-vtk-js/pull/94

**Pull request closed without merging**
