### PR TITLE
fix(XMLWriter): Bunp vtk.js version to fix crash when using XMLWriter

### PR DESCRIPTION
**Pull request by tamaynard**
Getting "Uncaught TypeError: pako__WEBPACK_IMPORTED_MODULE_1__.default.deflate is not a function" when attempting to use XMLWriter. Bumping should fix this.

### CODE REVIEW

**Review by sankhesh — COMMENTED** [review]
Are the changes in the package-lock file intentional? They seem to be removing the original dependencies and bringing in different ones.

**Comment by tamaynard** [comment]
Yes, I just followed the procedure as in https://github.com/Kitware/react-vtk-js/commit/7fc434c795bd3b0d61b58e6345d4654d972fc556 to update vtk.js. I tested against the latest versions of node and npm and didn't find any issues.

**Comment by floryst** [comment]
I think this might be due to react-vtk-js still inadvertently bundling parts of vtk.js. In any case, the changes look fine for now, but there's still an underlying issue.

**Comment by tamaynard** [comment]
Yes it's not ideal at all. But for now this was the path of least resistance.

**Pull request merged**
