### PR TITLE
Expose TubeFilter

### PR DESCRIPTION
**Pull request by tamaynard**
Exposes the vtkTubeFilter class for use in `<Algorithm />` blocks.

### CODE REVIEW

**Comment by jourdain** [comment]
Oups I merged too fast. If your commit message was using comitizen/semantic-release it would have been capture in the change log and generated a new version automatically.

**Comment by tamaynard** [comment]
Ahh thanks for the heads up @jourdain

**Comment by tamaynard** [comment]
Can you still force a release @jourdain? Would be nice to get this published to npm.

**Comment by jourdain** [comment]
Just create another PR fixing readme or else with a commit message `fix(TubeFilter): Expose it to Algorithm`

**Pull request merged**
